{% set name = "exa" %}
{% set version = "0.3.9" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz

build:
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - seaborn
    - networkx
    - pandas
    - notebook
    - nose
    - numba
    - six
    - pytables
    - sphinx
    - sphinx_rtd_theme
    - pandoc
    - nbsphinx

test:
  imports:
    - exa

about:
    home: https://exa-analytics.github.io/{{ name }}
    license: Apache-2.0
    license_file: LICENSE
    summary: A framework for data processing, computation, and visualization.
