{% set name = "exatomic" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: dist/{{ name }}-{{ version }}.tar.gz

build:
  number: 0

requirements:
  host:
    - pip
    - python
  run:
    - python
    - exa>=0.5.24
    - six>=1.0
    - numexpr>=2.0
    - ipywidgets>=7.0
    - bokeh
    - scipy>=1.4

test:
  imports:
    - {{ name }}

about:
    home: https://github.com/exa-analytics/{{ name }}.git
    license: Apache-2.0
    license_file: LICENSE
    summary: A unified platform for theoretical and computational chemists
