{% set name = "exatomic" %}
{% set version = "0.5.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/exa-analytics/{{ name }}/archive/v{{ version }}.tar.gz

requirements:
  build:
    - python
    - setuptools

  run:
    - numpy
    - pandas
    - numba
    - seaborn
    - ipywidgets
    - sympy
    - numexpr
    - exa
    - sympy
    - symengine
    - pyyaml

test:
  imports:
    - exatomic

about:
    home: https://exa-analytics.github.io/{{ name }}
    license: Apache-2.0
    license_file: LICENSE
    summary: A unified platform for theoretical and computational chemists
