# -*- coding: utf-8 -*-
# Copyright (c) 2015-2017, Exa Analytics Development Team
# Distributed under the terms of the Apache License 2.0
"""
This package provides a unified data format for organizing, analyzing, and
visualizing data coming from the most common computational chemistry software
programs.
"""
# Import base modules

# Import sub-packages

# Import user/dev API
from exatomic._version import __version__, version_info


def _jupyter_nbextension_paths():
    """
    Automatically generated by the `cookiecutter`_.

    .. _cookiecutter: https://github.com/jupyter/widget-cookiecutter
    """
    return [{
        'section': 'notebook',
        'src': '../build/widgets',
        'dest': 'jupyter-exatomic',
        'require': 'jupyter-exatomic/extension'
    }]
