package:
  name: exatomic
  version: "0.2.14"

source:
  git_rev: v0.2.14
  git_url: https://github.com/exa-analytics/exatomic.git

build:
  preserve_egg_dir: True

requirements:
  build:
    - python >=3.4
    - numpy
    - scipy
    - matplotlib
    - sqlalchemy
    - pandas >=0.18.1
    - networkx
    - sympy
    - seaborn
    - jupyter
    - notebook ==4.1.0
    - ipywidgets ==4.1.1
    - ipyparallel
    - sphinx
    - nose
    - exa
  run:
    - python >=3.4
    - numpy
    - scipy
    - matplotlib
    - sqlalchemy
    - pandas
    - networkx
    - sympy
    - seaborn
    - jupyter
    - notebook ==4.1.0
    - ipywidgets ==4.1.1
    - ipyparallel
    - sphinx
    - nose
    - exa


about:
  home: https://github.com/exa-analytics/exatomic
  license: Apache 2.0
  license_file: LICENSE
